_target_: mass.data.dataset.load_dataset
name: FER2013
preprocess_fn: ???
hf_dataset: 
  _target_: mass.data.dataset.load_fer2013
label_map: null
classnames_override: 
  - angry
  - disgusted
  - fearful
  - happy
  - neutral
  - sad
  - surprised