_target_: mass.data.dataset.load_dataset
name: KenyanFood13
ft_epochs: -1
preprocess_fn: ???
batch_size: 128
hf_dataset:
  _target_: mass.data.dataset.load_imagefolder_dataset
  data_files:
    train: "${oc.env:PROJECT_ROOT}/data/KenyanFood13/Food13/train/**"
    validation: "${oc.env:PROJECT_ROOT}/data/KenyanFood13/Food13/val/**"
    test: "${oc.env:PROJECT_ROOT}/data/KenyanFood13/Food13/test/**"
  cache_dir: "${oc.env:PROJECT_ROOT}/storage/hf_cache"
