_target_: mass.data.language.glue_load_dataset.load_glue_dataset
name: mnli
tokenizer: ??
batch_size: 128
cache_dir: null
split: validation_matched # validation_matched, validation_mismatched, test_matched, test_mismatched, test