model_name: ViT-L-14 # ViT-B-32, ViT-L-14
layer_to_hook: model.visual.transformer.resblocks.20.mlp.c_fc
openclip_cachedir: ${misc.openclip_cachedir}
model:
  _target_: mass.utils.io_utils.load_model_from_hf
  model_name: ViT-L-14
  dataset_name: base

