
defaults:
  - _self_
  - encoder: b32 #b16, b32, l14

_target_: mass.pl_module.image_classifier.ImageClassifier
x_key: ${conventions.x_key}
y_key: ${conventions.y_key}
dataset_names: {eval_dataset}

image_encoder: ??  
classification_heads: ??
